version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@types/chai"
    versions:
    - 4.2.15
    - 4.2.16
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
    - 8.3.2
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.1
    - 4.3.3
    - 4.3.4
  - dependency-name: typescript
    versions:
    - 3.9.9
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: lint-staged
    versions:
    - 10.5.4
  - dependency-name: ts-node
    versions:
    - 9.1.1
  - dependency-name: eslint-config-materya
    versions:
    - 7.0.2
    - 7.1.0
    - 7.1.1
